#' SCATE Pipeline
#'
#' SCATE pipeline of reading in bam, clustering cell, and performing SCATE 
#'
#' This function takes as input a list of bam files. It then read in the bam files, cluster cells, and performs SCATE for each cell cluster
#' @param bamfile Character vector of bam files to be processed
#' @param genome Character variable of either "hg19" or "mm10".
#' @param ncores Numeric variable of number of cores to use. If NULL, the maximum number of cores is used.
#' @param perplexity Numeric variable specifying perplexity of tSNE. Reduce perplexity when sample size is small.
#' @return A list of two elements. First element is a list generated by cellcluster function, and it contains the cell clustering results. Second element is a matrix generated by SCATE function. Each column is the SCATE result for one cell cluster. Columns are ordered by clusters: first column is the result for cell cluster 1, second column is for cluster 2,...
#' @export
#' @import GenomicAlignments parallel splines2 xgboost
#' @author Zhicheng Ji, Weiqiang Zhou, Hongkai Ji <zji4@@zji4.edu>
#' @examples
#' f <- list.files(paste0(system.file(package="SCATE"),"/extdata/example"),full.names = T)
#' SCATEpipeline(f,genome="hg19",perplexity=5)

SCATEpipeline <- function(bamfile,genome,ncores=detectCores(),perplexity=30) {
      satac <- sapply(sapply(bamfile,readGAlignmentPairs),GRanges)
      suppressWarnings(satac <- satacprocess(satac))
      cellclu <- cellcluster(satac,genome=genome,perplexity=5)
      SCATEres <- sapply(sort(unique(cellclu$cluster)),function(i) {
            SCATE(satac[cellclu$cluster==i],genome=genome)
      })
      list(cellcluster=cellclu,SCATEres=SCATEres)
}

